const KEY='hydra-water-v1';
const defaultContainers=[
 {id:'cup250',name:'Copo',volumeMl:250,icon:'🥛'},
 {id:'cup400',name:'Copo grande',volumeMl:400,icon:'🥤'},
 {id:'bottle500',name:'Garrafinha',volumeMl:500,icon:'💧'},
 {id:'bottle1000',name:'Garrafa 1 L',volumeMl:1000,icon:'🧴'}
];
const defaultData={profile:{weightKg:'',mlPerKg:35},containers:defaultContainers,records:[]};
let data=loadData(); let chartRange='day'; let deferredInstall=null; let chartCanvas=document.getElementById('waterChart');
function loadData(){try{const saved=JSON.parse(localStorage.getItem(KEY)||'{}'); const profile={...defaultData.profile,...(saved.profile||{})}; if(profile.mlPerKg==null) profile.mlPerKg=35; delete profile.goalOverrideMl; return {...defaultData,...saved,profile}}catch{return structuredClone(defaultData)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function today(){
 const now=new Date();
 const y=now.getFullYear();
 const m=String(now.getMonth()+1).padStart(2,'0');
 const d=String(now.getDate()).padStart(2,'0');
 return `${y}-${m}-${d}`;
}
function fmtMl(v){return `${Math.round(v||0).toLocaleString('pt-BR')} ml`}
function goalForProfile(p){return Math.round(Number(p?.weightKg||0)*Number(p?.mlPerKg||35))||0}
function goal(){return goalForProfile(data.profile||{})}
function dateLabel(d){return new Date(`${d}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'}).replace('.','')}
function dayTotal(d){return data.records.filter(r=>r.date===d).reduce((s,r)=>s+r.volumeMl,0)}
function localDateKey(date){
 const y=date.getFullYear();
 const m=String(date.getMonth()+1).padStart(2,'0');
 const d=String(date.getDate()).padStart(2,'0');
 return `${y}-${m}-${d}`;
}
function dateDaysBack(n){
 const a=[];
 const d=new Date();
 d.setHours(12,0,0,0);
 for(let i=n-1;i>=0;i--){
  const x=new Date(d);
  x.setDate(d.getDate()-i);
  a.push(localDateKey(x));
 }
 return a;
}
function allDaily(){const map={};data.records.forEach(r=>map[r.date]=(map[r.date]||0)+r.volumeMl);return map}
function average(arr){return arr.length?arr.reduce((a,b)=>a+b,0)/arr.length:0}
function render(){renderHome();renderContainers();renderSettings();renderHistory();renderChart()}
function renderHome(){const d=today(), g=goal(), c=dayTotal(d), pct=g?Math.min(100,Math.round(c/g*100)):0;document.getElementById('todayLabel').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'});document.getElementById('consumedToday').textContent=fmtMl(c);document.getElementById('goalToday').textContent=fmtMl(g);document.getElementById('progressPct').textContent=pct+'%';document.getElementById('remaining').textContent=fmtMl(Math.max(0,g-c));const ring=document.getElementById('progressRing');ring.style.background=`conic-gradient(#fff ${pct*3.6}deg,rgba(255,255,255,.18) 0deg)`;const days=dateDaysBack(7), vals=days.map(dayTotal);document.getElementById('avg7').textContent=fmtMl(average(vals));document.getElementById('goalDays').textContent=`${vals.filter(v=>g&&v>=g).length}/7`;const rows=data.records.filter(r=>r.date===d).sort((a,b)=>b.time.localeCompare(a.time));document.getElementById('todayLog').innerHTML=rows.length?rows.map(r=>`<div class="log-row"><div class="log-main"><span class="log-icon">${r.icon||'💧'}</span><div><div class="log-name">${escapeHtml(r.containerName||'Água')}</div><div class="log-time">${r.time}</div></div></div><span class="log-volume">+${fmtMl(r.volumeMl)}</span></div>`).join(''):'<div class="empty">Nenhum registro ainda. Toque em um recipiente para começar.</div>'}
function renderContainers(){document.getElementById('quickContainers').innerHTML=data.containers.map(c=>`<button class="container-btn" data-add="${c.id}"><span class="container-icon">${c.icon}</span><strong>${escapeHtml(c.name)}</strong><small>${c.volumeMl} ml</small></button>`).join('');document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addWater(b.dataset.add));document.getElementById('containerList').innerHTML=data.containers.map(c=>`<div class="setting-row"><span class="setting-icon">${c.icon}</span><div class="setting-info"><strong>${escapeHtml(c.name)}</strong><small>${c.volumeMl} ml</small></div><button class="small-btn" data-edit="${c.id}">Editar</button><button class="small-btn" data-delete="${c.id}">Excluir</button></div>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openContainerModal(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteContainer(b.dataset.delete))}
function renderSettings(){const p=data.profile||{};document.getElementById('weightInput').value=p.weightKg||'';document.getElementById('mlPerKgInput').value=p.mlPerKg??35;document.getElementById('calculatedGoal').textContent=fmtMl(goalForProfile(p))+'/dia'}
function renderHistory(){const daily=allDaily(), vals=Object.values(daily);document.getElementById('avgAll').textContent=fmtMl(average(vals));document.getElementById('maxDay').textContent=fmtMl(vals.length?Math.max(...vals):0);document.getElementById('daysRecorded').textContent=Object.keys(daily).length;const input=document.getElementById('historyDate');if(!input.value)input.value=today();renderHistoryDay(input.value)}
function renderHistoryDay(d){const rows=data.records.filter(r=>r.date===d).sort((a,b)=>a.time.localeCompare(b.time));const total=dayTotal(d);document.getElementById('historyDaySummary').innerHTML=`<div class="calculated" style="margin-top:14px"><span>${new Date(`${d}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})}</span><strong>${fmtMl(total)}</strong></div>${rows.length?rows.map(r=>`<div class="log-row"><div class="log-main"><span class="log-icon">${r.icon||'💧'}</span><div><div class="log-name">${escapeHtml(r.containerName||'Água')}</div><div class="log-time">${r.time}</div></div></div><span class="log-volume">+${fmtMl(r.volumeMl)}</span></div>`).join(''):'<div class="empty">Sem registros neste dia.</div>'}`}
function chartData(){const daily=allDaily();if(chartRange==='day'){const d=today();const hours=Array.from({length:24},(_,i)=>String(i).padStart(2,'0')+'h');const vals=hours.map((_,i)=>data.records.filter(r=>r.date===d&&Number(r.time.slice(0,2))===i).reduce((s,r)=>s+r.volumeMl,0));let sum=0,count=0;const avg=vals.map(v=>{sum+=v;count++;return sum/count});return {labels:hours,vals,avg}}if(chartRange==='week'){const labels=dateDaysBack(7);return makeDailySeries(labels,daily)}if(chartRange==='month'){const d=new Date(), y=d.getFullYear(),m=d.getMonth();const labels=[];for(let i=1;i<=new Date(y,m+1,0).getDate();i++)labels.push(`${y}-${String(m+1).padStart(2,'0')}-${String(i).padStart(2,'0')}`);return makeDailySeries(labels,daily)}const y=new Date().getFullYear();const labels=[];for(let m=0;m<12;m++)labels.push(`${y}-${String(m+1).padStart(2,'0')}-01`);const vals=labels.map((_,m)=>data.records.filter(r=>r.date.startsWith(`${y}-${String(m+1).padStart(2,'0')}`)).reduce((s,r)=>s+r.volumeMl,0));let sum=0;const avg=vals.map((v,i)=>(sum+=v)/(i+1));return {labels:labels.map(x=>new Date(`${x}T12:00:00`).toLocaleDateString('pt-BR',{month:'short'}).replace('.','')),vals,avg}}
function makeDailySeries(labels,daily){const vals=labels.map(d=>daily[d]||0);let sum=0;return {labels:labels.map(dateLabel),vals,avg:vals.map((v,i)=>(sum+=v)/(i+1))}}
function renderChart(){const ctx=chartCanvas.getContext('2d'),{labels,vals,avg}=chartData();ctx.clearRect(0,0,chartCanvas.width,chartCanvas.height);const rect=chartCanvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1;chartCanvas.width=rect.width*ratio;chartCanvas.height=rect.height*ratio;ctx.scale(ratio,ratio);const w=rect.width,h=rect.height,p={l:42,r:12,t:18,b:32},cw=w-p.l-p.r,ch=h-p.t-p.b;const max=Math.max(goal(),...vals,...avg,500);const x=i=>p.l+(labels.length===1?cw/2:i*(cw/(labels.length-1)));const y=v=>p.t+ch-(v/max)*ch;ctx.strokeStyle='#e6eeec';ctx.lineWidth=1;ctx.font='10px system-ui';ctx.fillStyle='#78908d';for(let i=0;i<4;i++){const yy=p.t+ch*i/3;ctx.beginPath();ctx.moveTo(p.l,yy);ctx.lineTo(w-p.r,yy);ctx.stroke();ctx.fillText(Math.round(max*(1-i/3)).toLocaleString('pt-BR'),4,yy+3)}function line(series,dash){ctx.beginPath();series.forEach((v,i)=>{const xx=x(i),yy=y(v);i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)});ctx.strokeStyle=dash?'#f59e0b':'#0f766e';ctx.lineWidth=2.5;ctx.setLineDash(dash?[5,5]:[]);ctx.stroke();ctx.setLineDash([]);series.forEach((v,i)=>{if(series.length>20&&i%Math.ceil(series.length/10)!==0)return;ctx.fillStyle=dash?'#f59e0b':'#0f766e';ctx.beginPath();ctx.arc(x(i),y(v),3,0,Math.PI*2);ctx.fill()})}line(vals,false);line(avg,true);ctx.fillStyle='#78908d';ctx.textAlign='center';const step=Math.max(1,Math.ceil(labels.length/7));labels.forEach((l,i)=>{if(i%step===0||i===labels.length-1)ctx.fillText(l,x(i),h-10)});}
function addWater(id){const c=data.containers.find(x=>x.id===id);if(!c)return;const now=new Date();data.records.push({id:crypto.randomUUID(),date:today(),time:now.toTimeString().slice(0,5),volumeMl:Number(c.volumeMl),containerId:c.id,containerName:c.name,icon:c.icon});save();render();toast(`+${c.volumeMl} ml adicionados`)}
function openContainerModal(id){const c=data.containers.find(x=>x.id===id);document.getElementById('modalTitle').textContent=c?'Editar recipiente':'Adicionar recipiente';document.getElementById('containerId').value=c?.id||'';document.getElementById('containerName').value=c?.name||'';document.getElementById('containerVolume').value=c?.volumeMl||'';document.getElementById('containerIcon').value=c?.icon||'💧';document.getElementById('modal').hidden=false}
function deleteContainer(id){if(!confirm('Excluir este recipiente? Os registros antigos serão mantidos.'))return;data.containers=data.containers.filter(c=>c.id!==id);save();render()}
document.getElementById('containerForm').onsubmit=e=>{e.preventDefault();const id=document.getElementById('containerId').value||crypto.randomUUID();const item={id,name:document.getElementById('containerName').value.trim(),volumeMl:Number(document.getElementById('containerVolume').value),icon:document.getElementById('containerIcon').value.trim()||'💧'};const idx=data.containers.findIndex(c=>c.id===id);idx>=0?data.containers[idx]=item:data.containers.push(item);save();document.getElementById('modal').hidden=true;render();toast('Recipiente salvo')};
document.querySelectorAll('[data-close-modal]').forEach(x=>x.onclick=()=>document.getElementById('modal').hidden=true);document.getElementById('addContainerBtn').onclick=()=>openContainerModal();document.getElementById('customAddBtn').onclick=()=>{const ml=prompt('Quantos ml você bebeu?');const v=Number(ml);if(v>0){const now=new Date();data.records.push({id:crypto.randomUUID(),date:today(),time:now.toTimeString().slice(0,5),volumeMl:v,containerName:'Volume personalizado',icon:'💧'});save();render();toast(`+${v} ml adicionados`)}};
function updateCalculatedGoal(){const w=Number(document.getElementById('weightInput').value)||0;const mlkg=Number(document.getElementById('mlPerKgInput').value)||0;document.getElementById('calculatedGoal').textContent=fmtMl(Math.round(w*mlkg))+'/dia'}document.getElementById('weightInput').oninput=updateCalculatedGoal;document.getElementById('mlPerKgInput').oninput=updateCalculatedGoal;document.getElementById('saveProfileBtn').onclick=()=>{data.profile.weightKg=Number(document.getElementById('weightInput').value)||'';data.profile.mlPerKg=Number(document.getElementById('mlPerKgInput').value)||35;save();render();toast('Perfil salvo')};
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));function switchView(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById('view-'+view).classList.add('active');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'});if(view==='home')renderChart()}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{chartRange=b.dataset.range;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderChart()});document.getElementById('historyDate').onchange=e=>renderHistoryDay(e.target.value);
document.getElementById('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`hydra-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)};document.getElementById('importInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const incoming=JSON.parse(reader.result);if(!Array.isArray(incoming.records)||!Array.isArray(incoming.containers))throw Error();data=incoming;save();render();toast('Dados importados')}catch{alert('Arquivo inválido.')}};reader.readAsText(file)};document.getElementById('clearDataBtn').onclick=()=>{if(confirm('Isso apagará perfil, recipientes e histórico. Continuar?')){localStorage.removeItem(KEY);data=structuredClone(defaultData);render();toast('Dados apagados')}};
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1800)}function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.addEventListener('resize',renderChart);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;document.getElementById('installBtn').hidden=false});document.getElementById('installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null}};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}));
render();
